name: Github Package Report

on:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      
      # Required for access to the GitHub Container Registry manifests
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - run: npm ci
      - run: npm run build
      
      - uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_ORG: ${{ secrets.GH_ORG }}
          PACKAGE_TYPE: container
          RETENTION: 365
        with:
          script: |
            const { default: packageReport } = await import('${{ github.workspace }}/dist/index.js')
            await packageReport()

      - run: ls -la

      - name: Set current date as env variable
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
  
      - uses: actions/upload-artifact@v3
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
        with:
          name: Results-Output-${{ env.TIMESTAMP }}
          path: out/*
          retention-days: 3
